# -*- coding: utf-8 -*-
"""CALCULATE_DNL_INL_FROM_MAESTRO_MARKERS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrSyWq1ZpHYsRyUc7qUugoq0QVDSLd5Z
"""

# A00096048
# DEAN WINTERS 2026
# dean.winters4@mail.dcu.ie

# This is a simple script created to calculate DNL and INL figures obtained from Cadence maestro simulation of respective
# DAC-architecture schematics.

# The values are obtained by setting markers in the Cadence maestro view and exporting the outputs as a .csv file
# Simple handling via pandas/Python was chosen as a natural choice for lightweight calculations such as these.

import pandas as pd
import numpy as np

# filename
#df = pd.read_csv("markers.csv")
#df = pd.read_csv("fahmy_thermometer_markers.csv")
#df = pd.read_csv("fahmy_thermometer_nonlinear_trial_markers.csv")

RESOLUTION = 8



def filter_cols(dataframe):

  # Hard code the column names which contain the pertinent marker voltage data.
  # Relies on a RESOLUTION param defined up top (since the no of markers is dependent on the voltage levels, i.e.: DAC resolution)
  # Then filter out irrelevant columns
  cols = []

  for i in range(1,RESOLUTION+2): #e.g.: 8 bit will have 9 markers including min and max Vout... V1 through V9
    cols.append(f"V{i}")

  return dataframe[cols]
#debug
#markers_df = filter_cols(df)
#print(markers_df)



def extract_t_v(dataframe):
  # Procures each marker(time, Voltage) value

  idx = [] # not used yet in any real capacity, is just included as good practice to append a key for each data row (or sanity check on number of markers/resolution)
  t = [] # time [s] at each marker
  Vout = [] # Voltage at V_out [V] at each marker

  for i in dataframe:
    col = dataframe[i]

    # Get time values from first row
    #np.float(64) check stops some reading error
    if isinstance(col[0], np.float64):
      t.append(col[0])

    # Sometimes Cadence format exports the voltage marker readouts on second row, but sometimes this is blank and read on third row, have a simple check
    # to see if empty (nan), then skip that second row and go to the third instead
    if isinstance(col[1], np.float64) and not np.isnan(col[1]):
      Vout.append(col[1])
    else:
      Vout.append(col[2])

  # Map the indices
  for i in range(0,len(t)):
    idx.append(i)

  return idx, t, Vout

#debug
#index, time, voltage = extract_t_v(markers_df)
#print(index)
#print(time)
#print(voltage)




def calculate_DNL_INL(idx, t, Vout):
  # Calculations

  # Ideal step size is just the aggregated net difference
  lsb_ideal = (Vout[-1] - Vout[0]) / (len(Vout) - 1)

  # Actual steps between each marker
  step = [Vout[i] - Vout[i-1] for i in range(1,len(Vout))]

  # DNL: ideal and observed steps differential [LSB]
  DNL = [(s-lsb_ideal) / lsb_ideal for s in step]

  # INL: cumsum of DNL at each marker
  INL = [sum(DNL[:i+1]) for i in range(len(DNL))]

  #print("LSB ideal:", lsb_ideal)
  #print("Steps:", step)
  #print("DNLs:", DNL)
  #print("INLs:", INL)
  #print("\n")

  # Or given as a max for reporting:
  DNL_max = float(max(abs(val) for val in DNL))
  INL_max = float(max(abs(val) for val in INL))

  print("Max DNL = ", DNL_max)
  print("Max INL = ", INL_max)

  return DNL_max, INL_max




def execution_helper(filename):
  # Bundle together in a single executable func for easier comparison between maestro sims

  print(f"\n FOR FILE: {filename} \n")
  df = pd.read_csv(filename)

  markers_df = filter_cols(df)

  index, time, voltage = extract_t_v(markers_df)

  DNL, INL = calculate_DNL_INL(index, time, voltage)

  return DNL, INL




execution_helper("fahmy_thermometer_markers.csv")
execution_helper("fahmy_thermometer_nonlinear_trial_markers.csv")

